### ISSUE TITLE
项目主题讨论

### ISSUE THREAD

**Issue by Mina-yy** [Mina-yy/BPstory#1]
好的开始是成功的一半～我们先来确定BP的主题吧～
每人搞1-2个提案，写一些简单的demo和想法，贴在评论区，大家讨论确认最终题目。

提案截止时间：4.10
微信群讨论时间：4.10第一次讨论
最终题目敲定时间：4.15

**Comment by Mina-yy** [comment]
### 原始提案记录：
* 提案一：一粒粟、锄禾。。。
    * 一句话描述项目：汇集追求智慧的人，提炼元学科最小模型、故事、行动，运用认知科学原理深度学习。
    * 目标用户：某个学科专家、深度爱好者、付费小白
        * 知识提炼者：攻克一手知识（前沿论文、大部头书目），提炼最小知识清单，输出知识卡片
        * 知识转化者：将最小知识清单转化成故事（视觉化、短视频。。。），输出故事卡片
        * 知识行动者：开发一些利用知识的小任务，符合最小行动原则，输出行动卡片
        * 吃瓜群众：付费刷卡包，可以对知识提出建议，是否接受由拥有者决定（github模式）—— 可去掉
    * 解决什么问题？
        * 终身学习时代的知识焦虑。运用认知科学原理，提炼学科内核，快速掌握最小模型、最小故事、提供最小行动，少走弯路。
        * 知识变现。有兴趣深挖某个学科的深度爱好者输出卡片，小白付费观摩，未来可输出体系学习教程
        * 元学科学习门槛高，爱好者望而却步。
        * 孤独的学习者。提供同侪压力、社群学习
    * 竞品：
        * 得到：门槛较低，三四手知识较多
        * 知乎：问答网站，模式不同，且开放使用后内容品质层次不齐
        * 果壳：更像科普网站，而不是“知识众筹”
    * 预期市场容量
* 提案二：夕阳红
    * 一句话描述项目：老年人兴趣社区
    * 解决什么问题：
        * 缺少兴趣的老年人，生活无聊
        * 老年人不愿接受新鲜事物，不敢尝试 —— 最小行动、反馈机制
* 提案三：卡片小工具
    * 我们可以设计一款开智部落小伙伴专门的卡片，比如设计一个笔袋，里面有卡片，简单的铅笔，橡皮，签字笔，里面的卡片都是写好的，比如，反常识卡，反常识，印象，例子等，你读书的时候拿出笔袋，填即可，减小了认知负担，我们可以利用这个讲故事，内切开智的学习模式。

---
第一个提案的出发点是早上和老大聊天想到的 真的发现所有的牛人思维方式都是差不多的 而且有差不多的方法论 如果能够复制这种方法论 做一个产品出来 能造福不少爱学习的小伙伴 不是都说终身学习嘛

第二个提案的出发点是我奶奶 过年的时候教会了奶奶画画 然后奶奶现在没两天发我一章她画的画 特别开心。在这之前我奶奶每天都没事做 只能看电视 但是奶奶耳朵又不好。我就想啊 现在很多上了年纪的人没有什么兴趣 又不懂的接受新鲜事物 生活太单调

**Comment by Mina-yy** [comment]
### 大家的思想碰撞记录：
提案一：
* 开智学员在这里面浸泡这么久了，除非能做的特别有新意，否则，一旦有漏洞，大家都轻而易举就识破了。
* 里面的东西太多了，太虚，太空。

提案二：
* 第二个方案可能更能打动人，更符合人类的生存优势规则。但是无论什么创意都要落细节和故事上，细节和故事才能打动人。
* 第二个的问题是什么样的最小行动可以激起老人的老人兴趣，而且兴趣那么多，是选某一种还是一批。找到一个可以具体着手的点。可以想想小孩子怎么培养兴趣的，胎教幼教啊，也许可以用在老人身上。
* 教练不是推荐我们看为孩子读诗吗？他们的目标人群是小孩，而小孩和老人都是容易触动情感的
* 老年人不该是在家里等待被陪伴，而是生活有自己的乐趣和精彩。
* 我们经常说发掘孩子的个性和潜力，干嘛不发掘老人的呢
* 我想起来，有个短篇，讲一个人给他母亲买了个机器人，然后机器人就每天陪母亲买菜，散步，一起吃饭，机器人没电时，老人会给它充电，有一天老人病倒了，机器人也给她充电。
* 做一个优雅漂亮温暖的老太婆

提案三：
* 受众太小，很难有好的商业模式
* 我们尽量不要以自己的视角看待商业问题 因为比较容易有认知偏差  现在在公司和产品讨论需求的时候 特别怕听到“我觉得。。”
* 用纸笔写卡片当然没有问题 现在不就可以做了么 要我们的产品做什么？解决了用户什么痛点？

---

鼓掌～ 呱唧呱唧～ 最终确定提案二！
让我们做一群性感的老年人！

**Comment by Mina-yy** [comment]
一下子就确认了主题！没想到这么顺利！忍不住多发一点感慨，实在太感恩碰到两位小伙伴！大家在微信群各种火花碰撞，各种好想法！和成长型的伙伴一起做事情简直太开心了！

**Comment by lucy201703** [comment]
### 大家的思想碰撞记录二（4月14日 菟葵 星星）
#### 项目名字
- 年轻的80岁
题目来源是初中读过的一篇文章[《年轻》](http://www.beeui.com/p/1561.html)，内容早已忘记，但一直记得“年轻的80岁”（die young at 80）。对文章印象深刻还有个小故事，初中毕业的暑假要做手术，随身带了一个日记本，本子里抄写了《年轻》，第一次做手术紧张，虽有麻醉药担心万一疼呢，临上手术台前一天默默地背下这篇文章，因为励志，手术台上被医生捅刀子的时候我在心里反复默诵《年轻》。当时年幼连年轻都还没经历，哪懂年轻的80岁，但隐约觉得这句话很酷。
- 从文章中提炼出性感词汇：初春 春色 重生 新生 婴儿 
#### 可能的故事
- 事件一：一个满脸皱纹的老人在家孤独的看电视、吃饭。。。。然后死去。。。亲人在追悼典礼上哭。 事件二：突然老人坐起来了（所以不能火化 哈哈） 然后老人觉得不应该这么度过晚年 然后镜头回放回到第一幕的画面。事件三：我们的产品出现 老年人开始获得新生。。。
- 故事还需要再性感一点 感觉做成定格动画一定很酷
- 故事结构可以，事件再打磨，如何衔接自然，阳老说不能在读者还没做好心理准备时让主人公死掉
#### 项目性质
- ——对了 我们好像还没决定我们是打算做公益还是商业？——商业吧 结合商业才能长久推广，也会更多有人愿意复制，虽然我们并不做起来，但是目标要宏伟！
#### 故事基调
- 死的场面可能有点沉重，除非我们加点什么元素活跃场面，我希望我们故事整体的基调是轻松活泼的，你们觉得有什么其它风格可以考虑
- 可以形成对比 比如第一次死的时候特别凄凉 第二次死的时候特别酷；总之中间需要一个很大的冲击 能让人意识到消极度日不好之类的
- ——死得很酷可以！但还是死会不会……让死变得不忌讳！——就看我们的表现手法了
#### 产品需求点
- 刚刚想到老人之间同侪压力，有两方面考虑：一是老人没有资源，他想做有意思的事情但可能不知道做啥，同侪可以相互分享资源和激发灵感；二是他有要做的事情但是不自信，同侪可以互成榜样相互鼓励
- 嗯嗯 老年还面临年龄大了之后不愿改变、很难容易新圈子的问题 需要我们产品打破这个现实问题 不然就广剩口号了；融入新圈子 认识新朋友；还有。。我们的产品字一定要大 哈哈
- 是否做成老人社群不清楚，不能光是老年人，圈子也要有年轻人。跟年轻人在一起更显年轻。还有老人的人生智慧不能浪费，用起来更有成就感
#### [对比另外一个也打老年人主意的项目](https://github.com/AIWriter/Writer004/issues/145)
- 人家是“陪”，我们是自己来；像我们这种以后的老人早就知道怎么玩了，哈哈；不过他们的产品也是有需求的，可以做铺垫，我们做升级
- 我们要想办法攻破老年人的第二序改变；我觉得侧重不一样 他们是实用派 我们主攻兴趣领域；他们是物质生活 我们要精神建设 哈哈哈
- >那么，如何引入第二序变化呢？书中引用哲学家维特根斯坦称，"如果我们不去问为什么而直接去探究现象所发生的重要事实，往往我们可以发现，事实会引导我们去找到答案。"既然系统内不存在可以去努力的部分，那就需要检查我们对问题（系统）的假设，然后重新框定问题所处的情境。也就是说，不要急于寻求问题的答案，而是重新审视问题本身，必要时换不同的角度阐释和界定问题，从而使问题在不同的系统间切换，那么，也许在某个新的系统内，问题的解是存在且显而易见的。

**Comment by lucy201703** [comment]
### 大家的思想碰撞记录三（4月15日 菟葵、星星、阿杰）
#### 项目的性质
*不论商业或公益，以讲打动人心的故事为主*
- 我们的项目是定位公益项目还是商业项目？我个人对做这个项目的看法是，讲一个打动人心的最小故事，尽量把课程中的知识，都用进去。或者说，项目只是载体，怎么用课程中的内容做才是重点。打动人心最重要，所以我觉得从公益项目的方向更好入手。
- 对 那是必须 不管商业还是公益都必须着眼故事的。公益的话可能很难有亮点 因为做老年公益的太多了。
- 我怎么感觉 故事效果是重点，课程内容是载体，看了我们故事后蠢蠢欲动。商业也可以打动人心的吧 但是我们不必太关注具体产品性能 主要是讲故事。
#### 故事框架
*我们搭建这个一个平台，然后老年人可以参与进来，从兴趣出发，实现自己的愿望*
- 我昨天的三件事是我想到的一个表现手法 如果能用定格动画就完美了 不过技术难度挑战很大。我昨天的突发奇想 主要是突出对比。
- ——还是阿杰的讲的，要打动人心，怎么让故事出来的画面动人
  ——嗯嗯 可能需要很多小细节 把心理活动全写在脸上
  ——我们先来头脑风暴一下事件一：没有我们产品之前的状态
- 我奶奶的状态是早上起床 出门散步 回来看电视（我奶奶耳朵不好 所以看电视就=发呆）中午吃饭 睡午觉 起来看电视 吃完饭 散步 睡觉
- 我没有跟爷爷奶奶生活的记忆，但我村子里的老人生活：抚育孩子、培养子女读书结婚生小孩，所有的娱乐似乎就是不用干活，然后默默终结一生
- 我希望这些一直付出的老人可以放飞自己的心灵，有时间和心思为自己活着。我有两个老人的故事：
大学时候，学校门口有一个拉二胡的老人，只要不下雨，无论刮风还是烈日，坐在教室里都能听到他拉二胡的声音。即使是七八月的三伏天，他带着一顶草帽三四点出来拉二胡拉到天黑。我跟他聊过天，他说他家里人嫌声音吵不让他拉，他就不如出来自在。
还有一个是我们村的老人，现在耳聋背驼，别人说话也听不见，听他儿媳妇说他一直想去香港看看，但谁会因为老人的一个念想，就专程儿带老父亲远赴香港，也许半途身体出状况。
这是我对这个BP感兴趣的初衷，我希望自己能帮助到他们，从最小行动帮助他们。
- ——我问几个问题吧，我们的项⽬是做什么的，产品最典型的⼀个或⼏个应⽤场景是什么？
  ——我觉得简单来说就是老年兴趣社群 特点是能够引发老年人的最小行动和二序改变（具体怎么做我还没想法） 应用场景应该是老年人通过我们的项目汇聚在一起做好玩的事情。刚冒出来一个想法 种子树 愿望墙那种 然后一群老人帮他实现
  ——难道是我想问题太现实了？总觉得，我们的初衷是好的，但是要做到打动人心好难。
  ——那我们的产品就是为老人提供实现愿望的平台？我们可以向身边老人搜集愿望，每个愿望背后应该有一个故事，挑选最动人的
  ——所以需要一个好故事呀；提供愿望实现和最初的兴趣可能方向不同 感觉更难落地
  ——对，是有点不同 现在还处于发散思维的过程。还是从兴趣出发，兴趣的的结果可实现最小愿望
  ——不过框架我觉得基本定了。使用前：无聊、孤独，使用后：充实、开心、满足 好像一个传销公司 哈哈哈哈
  ——2016开智大会里面有个项目就是是开智学堂，你们看过吗？我的理解是我们搭建这个一个平台，然后老年人可以参与进来，从兴趣出发，实现自己的愿望
  ——好的，思路清晰了，我们按照开智部落项目的模式先想想，这个平台提供的具体的兴趣点是什么？比如开智，以终生学习为主，读书，卡片大法，写作，机器学习，等等一系列具体的东西，然后围绕不同的领域，比如读书，又细分，然后组建部落，才有了同侪压力，共同学习，共同成长。那我们这个平台呢？总不能去跳广场舞吧，哈哈，开个玩笑
  ——我觉得我们关注兴趣前后的故事，然后不需要花大篇幅讲兴趣点。每个人的兴趣点都是独特的，画画 音乐 手工……把相同兴趣的人聚集一起，具体什么兴趣不是我们决定的，可以根据一个兴趣讲故事。
  ——我们选一个兴趣支撑怎么样？这样容易引发最小行动 另一方面其实我们支持的兴趣是可以扩展的，就好比淘宝店和淘宝的关系。
  ——经典的好的事，其实场景无非就三五个，然后通过这些场景的重复，不断推动故事的发展。
  ——具体细节打磨可以后期积累素材酝酿故事。今天是不是把BP公示做出来，我们可以把故事的任务放下周，每位伙伴寻找身边最小动人故事
#### 性感的名字
*初吻 枯木逢春 生活之吻*
*白首之心 白首之乐 白首学堂*
*烈焰 红发 骑士 老鸟 百鸟 白头翁*
*重生 逢春 种子 年轻的80岁 安详 宁静 云彩 夕阳无限好，只是近黄昏 青云之志*
*夕春* *骥之春*
- 我们找一个隐喻吧 可以从种子 愿望墙发散
- 名字一定要具象化，借助隐喻；最好有出处，会让人眼前一亮，不能光性感
- 初吻 枯木逢春 生活之吻 
- ——白首之心，黑白是符合人类生存原则的第一序列颜色的哦
  ——感觉太冷静了 我们是不是需要热烈一点的感觉
  ——老当益壮，宁移白首之心，穷且意坚，不坠青云之至/老骥伏枥志在千里 烈士暮年壮心不已
  ——白首之乐 白首学堂 白首，我觉的可以有，隐喻这是个老年人社群
  ——烈焰 红发 骑士 老鸟 百鸟 白头翁
  ——我发现，我是完全的男性化思维，你们是完全的女性化思维，哈哈，风格截然不同
  ——不同才能碰撞出好东西嘛
  ——我把画面放在了最后的老年阳光沙滩上了 夕阳红
  ——太俗了，木有新意 你自己说的，要性感
  ——我就是突然想到了 其实细细琢磨这是一个挺好的意象
  ——有一点，人们对这个词太熟悉了，看了后会有锚定效应，不好出新意，我的理解
- ——橙白 君裕 燕婉 仲举 子行 这些是我从第四章的卡片后面阳老师推荐的起名字软件里找的
  ——这些字太有文化了 感觉老年人不懂 可能是我太文盲了
  ——我们是给阳老师看的，哈哈 再说，不行还可以改啊
  ——我们给80岁的自己看，可还记得曾经有一群小年青？
- ——春意 怎么样？简单 有生存优势 符合年轻的80岁
  ——重生 逢春 种子 年轻的80岁 安详 宁静 云彩 夕阳无限好，只是近黄昏 青云之志 我拼凑不出一个意象
  ——春天就是一个意向呀 一切重新开始 新的生命
  ——如何赋予春天动感 我也想把春字用上 怎么结合
  ——嗯，我也这么想 夕春
  ——看字还行，读起来惜春
  ——挺好耶  不过会不会太冷静？
  ——春字意味着重新开始，我们需要再想一个隐喻老年人的字或词
  ——烈焰 红发 骑士 老鸟 怎么把菟葵的这种热烈放进去
  ——骥之春 骥取自老骥伏枥 春，焕发新的生命
  ——有意象啦，老人-骥 可以根据这个写故事，而且寓意好：一种能一日行千里的良马 怎么让老人保持这种体魄和精神
  ——我们可以把这些名字交给默认工作模式，说不定今天晚上洗澡的时候会有更好的，蹦出来
