### ISSUE TITLE
参考素材汇聚地

### ISSUE THREAD

**Issue by Mina-yy** [Mina-yy/BPstory#2]
有启发的都往这里丢吧！

**Comment by Mina-yy** [comment]
- [更换电池动画](http://v.youku.com/v_show/id_XMjU2MjU2NTAwMA==.html?from=s1.8-1-1.2&spm=a2h0k.8191407.0.0)
- [梦骑士](http://v.youku.com/v_show/id_XMzUzMjA4NDc2.html?from=y1.2-1-104.4.1-1.1-1-2-0-0%26source%3Dautoclick)
- [饺子的故事](http://v.youku.com/v_show/id_XNzI1MzczNzQ0.html?from=s1.8-1-1.2&spm=a2h0k.8191407.0.0)
- [奇怪的她](http://www.iqiyi.com/v_19rro4roow.html?fc=87451bff3f7d2f4a#vfrm=2-3-0-1)

**Comment by lucy201703** [comment]
- [第二序的变化——化不可能为可能](https://book.douban.com/review/7443547/)（来源：豆瓣读书《 改变－－问题形成和解决的原则》）
>那么，如何引入第二序变化呢？书中引用哲学家维特根斯坦称，"如果我们不去问为什么而直接去探究现象所发生的重要事实，往往我们可以发现，事实会引导我们去找到答案。"既然系统内不存在可以去努力的部分，那就需要检查我们对问题（系统）的假设，然后重新框定问题所处的情境。也就是说，不要急于寻求问题的答案，而是重新审视问题本身，必要时换不同的角度阐释和界定问题，从而使问题在不同的系统间切换，那么，也许在某个新的系统内，问题的解是存在且显而易见的。

**Comment by lucy201703** [comment]
- [《年轻》——塞缪尔·乌尔曼](http://www.beeui.com/p/1561.html)
>Youth is not a time of life; it is a state of mind. It is not a matter of rosy cheeks, red lips and supple knees. It is a matter of the will, a quality of the imagination, vigor of the emotions; it is the freshness of the deep spring of life.

**Comment by jason2960** [comment]
[老年人心理关爱的创新](http://www.doc88.com/p-0354342113113.html)
是否可以利用这篇文献中的数据，作为背景，及我们要解决的问题，或者查找相关的更新的数据和文献。

**Comment by jason2960** [comment]
# 老年人主题电影


### 华语片：

- [推手 (1991) ](https://movie.douban.com/subject/1306939/)

- [天堂回信 (1994)](https://movie.douban.com/subject/1418076/)

- [世界上最疼我的那个人去了 (2002)]()

- [世界上最疼我的那个人去了 (2002)](https://movie.douban.com/subject/1316565/)

- [我们俩 (2005) ](https://movie.douban.com/subject/1756073/)

- [我们天上见 (2009) ](https://movie.douban.com/subject/3732800/)



### 欧美片：

- [爱 Amour (2012)](https://movie.douban.com/subject/4798707/)

- [遗愿清单 The Bucket List (2007) ](https://movie.douban.com/subject/1867345/)

[]()


可以参考豆瓣的影评，看一部分，首推[遗愿清单 The Bucket List (2007) ](https://movie.douban.com/subject/1867345/)

**Comment by Mina-yy** [comment]
老年人口比例：http://www.gov.cn/xinwen/2016-07/11/content_5090300.htm
