### ISSUE TITLE
老树新芽产品设想

### ISSUE THREAD

**Issue by Mina-yy** [Mina-yy/BPstory#8]
老年人的故事平台：
收集老年人的人生阅历以及生活经验编成故事发布，选优秀的故事进行推广，打造老年IP。平台故事对所有人开放阅读，年轻人通过阅读更加理解老年人，并吸取老年人的经验，增进之间的情感联结。老年人通过阅读老年IP的经历激发自己的行动，改变自己的生活。
平台的故事就像一粒粒种子，由阅历丰富的老年人种下，在其他生命发出新芽。

角色：
    老年故事输出者（65岁以上）
    故事阅读者
    志愿者：采访志愿者、故事整理者（待定）

事件：
    老年写作：老人可以通过录音、写作等方式讲述自己的人生故事，也可以讲述自己现在的生活，发布在平台
    故事阅读：注册人可以阅读故事进行互动——点赞、评论
    采访老年人：选择有趣有料的老年人进行采访，把他们的故事编写成文发布在网站上，鼓舞其他老年人仿效

产品故事：
* 最小故事1：
    * 王奶奶身边无子女，生活无聊，每天散步吃饭睡觉，无所事事。。。
    * 王奶奶在我们的网站上看到一个奶奶讲述自己画画的故事（此处可以强势插入我奶奶的画 啊哈哈哈哈）
    * 王奶奶开始自己尝试作画，从此生活充满趣味。。。
* 最小故事2:（老年网瘾养成记 哈哈哈哈）
    * 王奶奶特别唠叨，喜欢给别人讲她年轻时候的故事，但是子女工作忙，没时间没耐心听她说，王奶奶特别失落
    * 王奶奶看到我们的网站广告，于是尝试把自己的故事发布在网站上
    * 王奶奶看到其他老年人给自己的故事点赞、评论，从此打开了新的社交圈子
* 最小故事3:
    * 王奶奶有一只破旧的缝纫机，使用的时候发出吱嘎嘎的噪音，家人觉得又破又占地方想给王奶奶换一个新式的全自动缝纫机，但王奶奶说什么也不肯扔掉
    * 家人突然有一天看到了王奶奶在网站上发布的她和缝纫机的故事。。。（此处需要有一段历史）突然理解了王奶奶对缝纫机的感情
    * 从此以后家人再也不阻止王奶奶使用这台缝纫机，甚至买来了缝纫机油 （缝纫机可以变换为各种旧物品：旧皮箱、旧电饭煲、旧衣服。。。）

产品原型：
![image](https://cloud.githubusercontent.com/assets/21056784/25654301/21433afc-3023-11e7-9584-f51604e68239.png)

**Comment by Mina-yy** [comment]
BP故事：

- 一口气讲三个最小故事，三个故事凑成一个复杂故事，三个故事的中心是网站，从不同方面反应网站的好处：提供老年人的行动动力；增进年轻&老年人之间的理解；故事分享打开老年人的社交。 最后推出我们的网站设计。
- 选择一个最小故事填充细节好好讲，最后推出我们的网站功能

大家觉得哪个方案好？我们需要在今晚确定其中一个，然后确定PPT的框架，开始填充细节。

**Comment by lucy201703** [comment]
`星星`：

**BP最小故事**（事件3>事件2>事件1、事件2导致事件3、事件3逆转事件1）
- **事件1**：王奶奶爱唠叨日常琐碎，儿孙忙工作忙学习没人听唠嗑（*老人现状*）
- **事件2**：儿子推荐了一款老树新芽app，听到许多同龄老人的故事，王奶奶忍不住拿起画笔用稚嫩的笔触开始老头子未完成的画和故事。（*体现产品功能：提供行动动力、分享故事*）
- **事件3**：网友的点赞和评论使奶奶深受鼓舞，于是奶奶画了一幅又一幅，讲了一个又一个故事。后来收到一个网友的真情表白，崇拜奶奶敢爱敢恨的青春，发现竟然是她上初中的孙女，还缠着她讲后面的故事。（*体现产品功能：增加社交互动、增进祖孙的感情*）

**Comment by lucy201703** [comment]
`阿杰`：

最小故事1
 
这里：老人在家里，盯着书桌上老伴的遗像，旁边是一幅未完成的画（要结合结尾的画，以及隐喻，设计具体的画），独自黯然神伤。他还记得她一辈子最大的愿望是能完成这幅画。
 
那里：一个画展上，梵高的《向日葵》前面，一个阳光帅气的小伙和一个时尚优雅的女孩，同时看着了很久这幅画，然后相互对视了10秒，相视而笑。就这样因同样喜欢画画，他们相遇，相知，相恋，相爱（可通过四个不同的场景图片表达出来）走入婚姻的殿堂。
 
然后通过一些日常生活场景的交替重复，显示时间的流逝，（中间插入一个或两个她们想要学画画却被生活或工作琐事打断，而一直没学的场景做铺垫）就这样，生活只剩下了生活，岁月苍老了他们的面容。
 
这里： 他们这辈子一起做的事情，一幕幕的在他眼前翻过（需要填充具体的细节和场景图片），画面定格在50年前，那个夕阳斜照的下午，那幅梵高的《向日葵》上，老人的眼角湿润了，脸上滑过一丝微笑。
 
引入我们的骥之春社区能提供什么样的服务或，平台，能做什么事情。
 
 最后结尾 屋内书桌上老伴的遗像，旁边那幅未完成的画替换成了另外一幅“门前老树长新芽，院里枯木又开花”的画（隐喻老人的成长，也找到了自己生命的价值和意义。）（这个可以由菟葵来画，甚至，我记得她奶奶就画的非常棒，如果能由奶奶自己画，效果会更好，情感指数一定很高。）屋外几个老人在一起悠然的画着画，讨论着画（画面中出现骥之春的标识）
 
按照同样的模型和思路

**Comment by lucy201703** [comment]
`星星`：

**BP最小故事v.1**
- 事件1：王奶奶坐在老伴的书房里，翻着他未画完的画册，抬起头惆怅地盯着墙上的遗像。再也没有谁可以像他一样陪着唠家常，朋友也一个个老去，儿孙又远在他乡。
- 事件2：王奶奶拄着拐杖来到公园，坐在长椅上和一群老太太晒太阳，听到她们津津乐道一款最近很火的“老树新芽”APP。王奶奶下载了“老树新芽”，点击一个个画面听着似曾相识的故事，终于忍不住拿起画笔用稚嫩的笔触开始老头子未完成的画，讲起她俩的故事。
- 事件3：在洒满阳光的院子里，孙女倚在王奶奶的身旁，问她：奶奶，爷爷当初为什么要画这些画？奶奶怔住了眼里泛着光：他说，为你喜欢。（最后插入老树新芽的画面，同时背景音乐响起《时间去哪儿了》：门前老树长新芽，院里枯树又开）

**Comment by lucy201703** [comment]
`菟葵`：

事件1：王奶奶爱唠叨日常琐碎，儿孙忙工作忙学习没人听唠嗑，老人叹口气 盯着书桌上老伴的遗像，从抽屉里拿出一幅未完成的画（要结合结尾的画，以及隐喻，设计具体的画），独自黯然神伤。
事件2：有一天，儿子推荐了一款老树新芽app，无聊的午后王奶奶听到一个80岁老人学画画的故事（我们的app提供听故事的功能），激发了王奶奶，她忍不住拿起画笔用稚嫩的笔触画一些简单的画作并上传到我们网站（可以用我奶奶的画做素材），获得了很多点赞，这些赞激励奶奶完成更多的作品。最后奶奶开始着手完成老头子未完成的画。
事件3：王奶奶把画上传到我们的网站，并添加了和老伴儿的爱情故事（此处是一个组块，需要一段煽情的小故事），获得了超多网友的点赞和关注（这里可以突出某一个网友对王奶奶的崇拜评论）。 很快新年到了，孙女回老家过年发现自己喜欢的网上的故事居然是自己的奶奶画的，于是缠着奶奶讲述后来的故事。门外，一颗老树长出了新芽。

**Comment by lucy201703** [comment]
`星星`：

**BP最小故事v.2**
- 事件1：在老伴的书房，翻着他过去为她画下的画册，惆怅地盯着墙上的遗像。再也没有谁可以像他一样陪着唠家常，朋友也一个个老去，儿孙又远在他乡。（背景音乐响起《时间去哪儿了》：门前老树长新芽，院里枯树又开）
- 事件2：王奶奶拄着拐杖来到公园，坐在长椅上和一群老太太晒太阳，听到她们津津乐道一款最近很火的“老树新芽”APP。王奶奶回到家下载了“老树新芽APP”，点击一个个画面听着别人的人生故事，内心的青春被唤醒，老头子用绘画为她记录了青春，如今他已不在，她要用文字续写她俩的故事。于是注册了“王奶奶和她老伴儿”的用户名，在“老树新芽”平台上分享了她俩的故事，配着他的画。
- 事件3：故事发布后，王奶奶意外收到许多网友的点赞和关注，纷纷鼓励连载她和老头的故事。还收到一位网友的热情表白，崇拜她敢爱敢恨的青春。春节儿女回家，在饭桌上谈起风靡一时的“王奶奶和她老伴儿”的连载故事，大家才发现是饭桌的这位王奶奶，热情表白的网友竟是上初中的孙女。

**Comment by lucy201703** [comment]
`星星`：

**BP最小故事v.3**
- 事件1：在老伴的书房，翻着他过去为她画下的画册，惆怅地盯着墙上的遗像。再也没有谁可以像他一样陪着唠家常，朋友也一个个老去，儿孙又远在他乡。（背景音乐响起《时间去哪儿了》：门前老树长新芽，院里枯树又开……）
- 事件2：王奶奶拄着拐杖来到公园，坐在长椅上和一群老太太晒太阳，听到她们津津乐道一款最近很火的“老树新芽”APP。王奶奶回家下载了“老树新芽APP”（*此处插入图片：APP启动的界面出现logo和口号“老树新芽，让故事唤醒你的青春”*），点击一个个音频听着别人的人生故事（*此处插入图片：菟葵设计的功能界面（故事栏有一些应景的故事标题）*），内心的青春被唤醒。老头子用绘画为她记录了青春，如今他已不在，她要用文字续写她俩的故事。于是注册了“王奶奶和她老伴儿”的用户名（*此处可或省略插入图片：登陆注册界面“），在“老树新芽”平台上分享了她俩的故事，配着他的画（*此处插入图片：菟葵设计的故事发布界面+老头的一幅应景的画（比如丰子恺或者老树画画风格的）*）。
- 事件3：故事发布后，王奶奶意外收到许多网友的点赞和关注（*此处插入图片：发布故事的互动界面（可能还得简单写一点王奶奶这篇故事的文字和网友的评论）*），纷纷鼓励连载她和老头的故事。还收到一位网友的真情表白，崇拜她敢爱敢恨的青春（*此处插入图片：网友的真情表白*）。端午节儿女回家，在饭桌上谈起风靡一时的“王奶奶和她老伴儿”的连载故事，大家才发现是饭桌的这位王奶奶，真情表白的网友竟是上初中的孙女。（*此处插入图片：饭桌上欢乐的一家（王奶奶和孙女是主角）*）王奶奶趁兴让家人一起用语音录了一段节日祝福，送给她的粉丝和圈里的朋友，感谢他们的支持和鼓励，让她重返青春。（*此处插入图片：体现语音功能*）
- 结尾：故事结束，出现老树新芽logo和一句话口号（老树新芽，让故事唤醒你的青春），同时响起“门前老树长新芽，院里枯木又开花”的旋律。

**Comment by lucy201703** [comment]
`菟葵`：

昨天隐隐觉得我们的故事有点问题 刚才看了很多其他案例 我想我们的故事还是太复杂了 我们把所有的产品功能和好处全部浓缩在一个故事里面 会让整个故事特别胖 不清爽。如果我们的故事用来写一个短片小说或者拍个小动画挺好的，但十几页的PPT似乎不足以承载这么大的信息量。

从另外一个角度说，我们目前想体现三个好处：1.收集老人的人生故事，激发他人的行动；2.加深子女对父母的了解；3.用点赞、评论等 打开老年社交。每个好处深挖下去都大有文章可做，产品设计的重点也会有不同，但是如果我们全部抓住都不想放弃的话，我怕每一项都浅尝辄止，观看的人更是一脸懵逼。

我们是不是能选取一个作为最小支点？比如如果我们想做老年生活方式的倡导，上传的故事必须是积极正面的，所以需要有专业团队进行信息加工，还必须花力气在老年人的阅读障碍上。。。如果要拉投资的话 这些应该是产品亮点，需要占用一些PPT篇幅，如果全部用来讲王奶奶的故事，感觉把产品特点什么的给淹没了。

就像“中国三明治”，他们其实是30岁人群的生活方式倡导平台，虽然它们也能够带来行动、带来理解、打开社交，但它们的slogon很简单：中国故事记录者/创新生活方式倡导者

**Comment by lucy201703** [comment]
`星星`：

你说的故事太复杂的问题确实存在，但确切地说，不是故事太复杂，而是故事太故事，与产品有些脱离。核心是产品，故事只是依托。我们现在是本末倒置，讲一个故事本是为了表现产品，我们好不容易设计一个产品却沦为讲一个故事。产品是内容，故事是形式，我们搞反了。

一开始看BP范例时有意识到，产品故事不是非要讲具体的故事，爱银发和红色就是，其实没有很具体的人物时间地点事件，而是用故事形式把功能串起来而不是罗列。

**Comment by lucy201703** [comment]
`星星`：

你说的故事太复杂的问题确实存在，但确切地说，不是故事太复杂，而是故事太故事，与产品有些脱离。核心是产品，故事只是依托。我们现在是本末倒置，讲一个故事本是为了表现产品，我们好不容易设计一个产品却沦为讲一个故事。产品是内容，故事是形式，我们搞反了。


`菟葵`：

对对对 就是这种感觉。我们对故事的定义有些太故事了 我看了老年银发的那个宣传片 他们也是讲故事 讲老年人失智的故事 但是讲的非常简单清楚 一下子就代入进去了。我们却像是在拍电影写小说的感觉。

我觉得是容易被“故事”这两个字给误导。我不知道你们会不会这样 我是一听故事两个字 第一感觉就是小说电影那样的情节 但后来发现这种对故事的定义非常狭隘 其实只要有细节、转折、隐喻，能够让人代入到另一种环境 理解表达的人想表达的内容 都是故事。

就像前几天我听到人类最伟大的故事是“钱”。因为每个人都相信手里的这张纸能够换取生活必需品。是一种意象的表达。

`星星`：

一开始看BP范例时有意识到，产品故事不是非要讲具体的故事，爱银发和红色就是，其实没有很具体的人物时间地点事件，而是用故事形式把功能串起来而不是罗列。

我昨天晚上写完故事还感觉哪里不对，写完后感觉是《把乐带回家》这种温情广告风格，但没有意识到问题在哪。

最小故事的三个事件，事件1是状态（问题），事件2是行动（解决方案），事件3是逆转（效果）。所以我们的产品故事就是表达可以解决什么问题，提供的解决方案是什么，效果如何。

`菟葵`：

 嗯嗯，然后添加细节进去，让别人能够直观感受到老年人面临的困境，我们产品的创新、最终的效果。

我记得哪节课上说人生的意义在于修辞 可能也是这个道理 不是人人都要会写出有文采的文章或是有转折的故事 而是找到人生的一种意象。

**Comment by lucy201703** [comment]
`星星`：

- **开头引导语**

年轻时用梦想和勇气演绎的青春故事，埋在心房的角落里。

五味杂陈的一生，你希望默默留下一纸遗像一盒骨灰，

还是讲出故事唤醒青春，为自己和他人的生命种下一颗种子待它发芽？

- **事件1**

王奶奶70岁了，时常忆起当年的粉颊红唇，却无处倾诉青春。

难得和孙女聊聊天讲起年轻的故事：奶奶以前啊……

回应只有“嗯嗯啊啊”，低头只顾刷手机。

- **过渡引导语**

生活不止眼前的苟且，可是哪里有诗和远方？

朋友一个个离去，儿孙常年奔波在外，公园的老太只有柴米油盐。

独坐电视前，羡慕着剧里的青春，听到电视里的一份故事征集令：

>老树新芽APP邀您续写年轻的故事，唤醒内心的青春，和一群朋友共聊诗和远方，为年轻一辈树立生活的榜样。

- **事件2**

王奶奶打开APP，翻阅一个个故事点击倾听。
故事栏目1：老有所乐——分享生命趣事，寻找志趣相同的伙伴共筑诗和远方
故事栏目2：吃过的盐——分享人生经历，为年轻一辈提供参考的方向
故事栏目3：健康之路——分享养生之道，为社会健康事业献一份力

王奶奶注册了“王奶奶和她的老伴儿”的用户名，在“故事小助手”的引导下讲起自己的青春，分享了她的爱情和老头的画，发布到“老有所乐”。

王奶奶的故事引起网友的点赞和关注，还遇到几位爱画画的老伙伴相约学画画。

- **事件3**

听着“门前老树长新芽，院里枯木又开花”的旋律，王奶奶写了一封信给天堂的他：

>老头子，想你了。
>
>我把我们的故事分享到“老树新芽APP”，很多人点赞呢，孙女现在可崇拜我了。我还找到一群伙伴一起学画画，你留下的未画完的画册，我帮你画上。看，这是我今天画的花。（此处可插入菟葵奶奶的画）

- **结尾**

老树新芽APP，一起用故事续写青春，待它重新发芽。

**Comment by Mina-yy** [comment]
我叫王老太 今年70岁 耳朵不好 轻度白内障 每天3个药片一杯糖浆
老伴儿走的早 只留下一张遗像 一本纪念我们恋爱故事的画册
有一个儿子一个儿媳 很孝顺 但工作忙 只有过年才能回来
又一个孙女 很可爱伶俐 但手机对她有无穷吸引力

老头子～ 法定退休年龄60岁 当人过了这个年龄啊 生活不再有任何惊喜
早上起床 散步 吃饭 发呆 睡觉
儿女偶尔电话视频 却总是匆匆忙忙 
到了这个年纪 身体不允许远行 连心灵好像也一起懦弱了  很难社交 很难做出一点点出格的事情
为何活了一辈子 生命浓度到达最高点时 却总是失落

唉。。。。

一天像往常一样散步 被推荐了 老树新芽
点开一篇篇老年人的故事 有人讲述自己年轻的辉煌 有人讲述学画画骑摩托车 有人组织老年旅行 发现老年生活还能这样
不仅支持文字 还支持音频
不仅能够阅读 还能创作自己的故事

现在的科技真是不得了！

我把我和老伴的爱情故事配上老伴儿的图册 上传到网上
文章写的很简单 却意外收获一堆点赞和评论
“强势插入一段留言”

看到这些留言 我仿佛又回到了年轻的时候 回到了恋爱的年纪

老头子 我还认识了一些画画的同好 你看这是我最近刚学的画 我准备呀 继续完成咱俩的故事。
对了 孙女现在可崇拜我了呢 每周都缠着我给她讲年轻时候的故事。
咱们老年人呐 到了这个年纪 身体不允许远行 心灵却是可以在路上的嘛！
生命的浓度开始散发酒一样的香味啦～     

老树新芽APP 老年生活方式倡导者
用故事续写青春，长出春天的嫩芽。
